/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xF4, 0xEF, 0x1A, 0xD7, 0x40, 0xCF, 0x31, 0xA7}

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define MIDI_ADVANCED

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define GRAVE_ESC_SHIFT_OVERRIDE

#define TAPPING_TERM 175


#define SELECT_WORD_TIMEOUT 2000
#define VIAL_COMBO_ENTRIES 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4