VIA_ENABLE = yes
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=5
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIALRGB_ENABLE = yes

LTO_ENABLE = yes

MIDI_ENABLE = yes

CAPS_WORD_ENABLE = yes

COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes

SRC += features/select_word.c
